// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAK4vsDDkFW9-7yrVzIEUSiimMaqbso9Lc",
    authDomain: "currensee-f1718.firebaseapp.com",
    projectId: "currensee-f1718",
    storageBucket: "currensee-f1718.firebasestorage.app",
    messagingSenderId: "455542611420",
    appId: "1:455542611420:web:6cc89154eb9d18a2fa8319",
    measurementId: "G-SH270GW9XT",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1IQ5oJKPTu1r06mjWhcukh7xvDa81rao',
    appId: '1:455542611420:android:6e7efacbed4e8eeafa8319',
    messagingSenderId: '455542611420',
    projectId: 'currensee-f1718',
    storageBucket: 'currensee-f1718.appspot.com',
  );
}
